name: Next js frontend dev

on:
  push:
    branches:
    - devxxxxxxxxx

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and deploy next app
      uses: razzkumar/pr-automation-with-s3@v1.0.2
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
        SRC_FOLDER: "out"
        ACTION: 'deploy'
        BUILD_COMMAND: "yarn build && yarn export"
        CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
        SECRETS_MANAGER: ${{ secrets.SECRETS_MANAGER }} // name of secrets on secret manager
